/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { Project } from "./Project";

export { Ownable__factory } from "./factories/Ownable__factory";
export { Project__factory } from "./factories/Project__factory";
